### DISCUSSION TITLE
Settings for MarkDown Extensions in `YAML` Front Matter

### DISCUSSION THREAD

**Discussion by RoyiAvital** [facelessuser/MarkdownPreview#129] [Show and tell]
It might be trivial to other users, but I think it should be written.

If you define the `YAML` front matter with `markdown_extensions`:

```
---
    # Settings overrides
    settings:
        enable_uml: true
        markdown_extensions:
          - markdown.extensions.footnotes
          - markdown.extensions.attr_list
          - markdown.extensions.admonition
          - markdown.extensions.md_in_html
          - pymdownx.highlight:
              pygments_style: github
          - pymdownx.progressbar
          - pymdownx.github
          - pymdownx.caret:
              superscript: false
---
```

It will override the whole struct. Namely if any extension is defined in the user settings but not there, it won't be enabled.
I thought this functionality is only to enable more extensions but it actually to set the whole settings state.

It makes sense, just needed to be accounted.
