### DISCUSSION TITLE
Use the `enable_uml` Feature

### DISCUSSION THREAD

**Discussion by RoyiAvital** [facelessuser/MarkdownPreview#146] [Q&A] [answered]
In a MarkDown document I use created the following frontmatter:

```yaml
---
    # Meta Data
    Title: Some Title
    Summary: Few Words
    Author:
        - Royi

    # Settings
    settings:
        enable_uml: true
        image_path_conversion: base64
        markdown_extensions:
          - markdown.extensions.footnotes
          - markdown.extensions.fenced_code
          - markdown.extensions.tables
          - markdown.extensions.admonition
          - markdown.extensions.md_in_html
          - markdown.extensions.toc:
                title: Table of Contents
                toc_depth: 2-3
          - pymdownx.arithmatex:
                generic: true
                smart_dollar: false
        allow_css_overrides: true
---
```

In my Markdown Preview settings I defined:

```json
{
    "js": {
        "markdown": [
            "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js",
            "res://MarkdownPreview/js/math_config.js",
            // Required libraries to transform UML notation
            "https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js",
            "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js",
            "https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js",
            "https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js",

            // This library applies the above libraries to the fenced code blocks `flow` and `sequence`.
            "res://MarkdownPreview/js/uml.js",
        ]
    },
```

I did that by following [UML Support](https://facelessuser.github.io/MarkdownPreview/extras/#uml-support).

The generated HTML has:

```
<html>
<body>
<!--StartFragment-->

</script><script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js'></script><script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'></script><script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js'></script><script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js'></script><script>(function () {
--
  | 'use strict';
  |  
  | /**
  | * Targets special code or div blocks and converts them to UML.
  | * @param {object} converter is the object that transforms the text to UML.
  | * @param {string} className is the name of the class to target.
  | * @param {object} settings is the settings for converter.
  | * @return {void}
  | */
  | var uml = (function (converter, className, settings) {
  |  
  | var getFromCode = function getFromCode(parent) {
  | // Handles `<pre><code>`
  | var text = "";
  | for (var j = 0; j < parent.childNodes.length; j++) {
  | var subEl = parent.childNodes[j];
  | if (subEl.tagName.toLowerCase() === "code") {
  | for (var k = 0; k < subEl.childNodes.length; k++) {
  | var child = subEl.childNodes[k];
  | var whitespace = /^\s*$/;
  | if (child.nodeName === "#text" && !whitespace.test(child.nodeValue)) {
  | text = child.nodeValue;
  | break;
  | }
  | }
  | }
  | }
  | return text;
  | };
  |  
  | var getFromDiv = function getFromDiv(parent) {
  | // Handles `<div>``
  | return parent.textContent \|\| parent.innerText;
  | };
  |  
  | // Change article to whatever element your main Markdown content lives.
  | var article = document.querySelectorAll("article");
  | var blocks = document.querySelectorAll("pre." + className + ",div." + className
  |  
  | // Is there a settings object?
  | );var config = settings === void 0 ? {} : settings;
  |  
  | // Find the UML source element and get the text
  | for (var i = 0; i < blocks.length; i++) {
  | var parentEl = blocks[i];
  | var el = document.createElement("div");
  | el.className = className;
  | el.style.visibility = "hidden";
  | el.style.position = "absolute";
  |  
  | var text = parentEl.tagName.toLowerCase() === "pre" ? getFromCode(parentEl) : getFromDiv(parentEl
  |  
  | // Insert our new div at the end of our content to get general
  | // typeset and page sizes as our parent might be `display:none`
  | // keeping us from getting the right sizes for our SVG.
  | // Our new div will be hidden via "visibility" and take no space
  | // via `position: absolute`. When we are all done, use the
  | // original node as a reference to insert our SVG back
  | // into the proper place, and then make our SVG visible again.
  | // Lastly, clean up the old node.
  | );
  | article[0].appendChild(el);
  | var diagram = converter.parse(text);
  | diagram.drawSVG(el, config);
  | el.style.visibility = "visible";
  | el.style.position = "static";
  | parentEl.parentNode.insertBefore(el, parentEl);
  | parentEl.parentNode.removeChild(parentEl);
  | }
  | });
  |  
  | (function () {
  | var onReady = function onReady(fn) {
  | if (document.addEventListener) {
  | document.addEventListener("DOMContentLoaded", fn);
  | } else {
  | document.attachEvent("onreadystatechange", function () {
  | if (document.readyState === "interactive") {
  | fn();
  | }
  | });
  | }
  | };
  |  
  | onReady(function () {
  | if (typeof flowchart !== "undefined") {
  | uml(flowchart, "uml-flowchart");
  | }
  |  
  | if (typeof Diagram !== "undefined") {
  | uml(Diagram, "uml-sequence-diagram", { theme: "simple" });
  | }
  | });
  | })();
  |  
  | }());
  | </script>

<!--EndFragment-->
</body>
</html>
```

The MarkDown text (The example in `flow-charts.js`):

```
\```flow
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...
para=>parallel: parallel tasks

st->op1->cond
cond(yes)->io->e
cond(no)->para
para(path1, bottom)->sub1(right)->op1
para(path2, top)->op1
\```
```

Generated this HTML:

```
<html>
<body>
<!--StartFragment-->

<pre><code class="flow">st=&gt;start: Start:&gt;http://www.google.com[blank]
--
  | e=&gt;end:&gt;http://www.google.com
  | op1=&gt;operation: My Operation
  | sub1=&gt;subroutine: My Subroutine
  | cond=&gt;condition: Yes
  | or No?:&gt;http://www.google.com
  | io=&gt;inputoutput: catch something...
  | para=&gt;parallel: parallel tasks
  |  
  | st-&gt;op1-&gt;cond
  | cond(yes)-&gt;io-&gt;e
  | cond(no)-&gt;para
  | para(path1, bottom)-&gt;sub1(right)-&gt;op1
  | para(path2, top)-&gt;op1
  | </code></pre>

<!--EndFragment-->
</body>
</html>
```

Yet nothing is rendered.

What am I doing wrong?

**Comment by facelessuser** [comment]
I don't have an answer yet, but it may be due to the fact that you are indenting your frontmatter when you don't need to, but I haven't run through your example yet.

**Reply by RoyiAvital** [reply]
I tried with the following front matter as well:

```
---
# Meta Data
Title: Some Title
Summary: Some Details
Author:
    - Royi

# Settings
settings:
    enable_uml: true
    image_path_conversion: base64
    markdown_extensions:
      - markdown.extensions.footnotes
      - markdown.extensions.fenced_code
      - markdown.extensions.tables
      - markdown.extensions.admonition
      - markdown.extensions.md_in_html
      - markdown.extensions.toc:
            title: Table of Contents
            toc_depth: 2-3
      - pymdownx.arithmatex:
            generic: true
            smart_dollar: false
      - pymdownx.arithmatex:
            custom_fences:
                name: mermaid
                class: mermaid
                format: pymdownx.superfences.fence_div_format
    allow_css_overrides: true
---
```

It still didn't work.
