### DISCUSSION TITLE
Working with `SuperFences`

### DISCUSSION THREAD

**Discussion by RoyiAvital** [facelessuser/MarkdownPreview#149] [Q&A] [answered]
It seems I can't get `SuperFences` to work on my file.
Specifically using a _custom fence_.

In the YAML I have this:

```
---
title: Report
summary: Just a report
author:
    - Royi
    - Or

settings:
    allow_css_overrides: true
    strip_yaml_front_matter: false
    image_path_conversion: base64

    js:
        - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js
        - res://MarkdownPreview/js/math_config.js
        - https://unpkg.com/mermaid@8.8/dist/mermaid.min.js

    markdown_extensions:
        - markdown.extensions.admonition
        - markdown.extensions.footnotes
        - markdown.extensions.tables
        - markdown.extensions.toc:
            title: Table of Contents
            toc_depth: 2-3
        - pymdownx.superfences:
            custom_fences:
                - name: mermaid
                  class: mermaid
                  format: pymdownx.superfences.fence_div_format
---
```

Yet for this code fence:

~~~
```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```
~~~

I get:

![image](https://user-images.githubusercontent.com/7347975/169717072-eac4ebf9-ed59-4206-b602-e23606d444d5.png)

Namely it doesn't yield any custom fence.

Here are the files to reproduce:
 - [TMP.md](https://github.com/facelessuser/MarkdownPreview/files/8750327/TMP.md).
 - [TMP.txt](https://github.com/facelessuser/MarkdownPreview/files/8750329/TMP.txt) (Change into `TMP.css`).

Another issue I saw, in case my user settings of MarkDown Preview is empty (Namely only: `{}`) the file above won't render at all. It seems the parsing of the `YAML` won't happen at all.

**Comment by facelessuser** [comment]
Did it work with the original example I gave using the old UML format? Is so, there shouldn't be much of a difference. What could be happening though I'd that the JS script isn't working like you think. 

You are using a div output for the custom fences, so it should just look like normal text until the JS loader transforms it.

**Reply by RoyiAvital** [reply]
I have just written below what I found to be working. Is it by design?

By the way, is this by design as well:
> Another issue I saw, in case my user settings of MarkDown Preview is empty (Namely only: `{}`) the file above won't render at all. It seems the parsing of the `YAML` won't happen at all.

**Comment by RoyiAvital** [comment]
OK, It seems documentation is wrong.
IF one looks at the UML Diagram Example at https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#uml-diagram-example, the code says: `'format': pymdownx.superfences.fence_div_format` which translates to what I wrote above.

Yet, in MarkDown Preview, the default config file configures custom fences as following:

![image](https://user-images.githubusercontent.com/7347975/169718362-28d8fac2-1823-473a-a803-8be5f6240b90.png)

Hence I tried:

```
        - pymdownx.superfences:
            custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_div_format
```

Which works (By the way, `format: !!python/name:pymdownx.superfences.fence_code_format` won't work).

Hence I suggest updating the documentation.
