### ISSUE TITLE
The `b64` Extension Doesn't Work in a Simple Use Case

### ISSUE THREAD

**Issue by RoyiAvital** [facelessuser/MarkdownPreview#130]
I have this simple user case for `b64`:

```
---
    # Meta Data
    Title: Admonitions Test

    # Settings
    settings:
        enable_uml: true
        markdown_extensions:
          - markdown.extensions.footnotes
          - markdown.extensions.tables
          - markdown.extensions.admonition
          - markdown.extensions.toc:
                toc_depth: 2-4
          - pymdownx.b64
        allow_css_overrides: true
---

## Testing B64

![](./GitHub.png)
```

Yet the generated HTML doesn't embed the image.

Here is the MWE:

[B64Test.zip](https://github.com/facelessuser/MarkdownPreview/files/6526650/B64Test.zip)

**Comment by facelessuser** [comment]
Works fine. Don't indent your YAML so much:

```
---
# Meta Data
Title: B64 Test

# Settings
settings:
    enable_uml: true
    markdown_extensions:
      - markdown.extensions.footnotes
      - markdown.extensions.tables
      - markdown.extensions.admonition
      - markdown.extensions.toc:
            toc_depth: 2-4
      - pymdownx.b64
    allow_css_overrides: true
---

## Testing B64

![](./GitHub.png)
```

<img width="611" alt="Screen Shot 2021-05-23 at 7 50 16 AM" src="https://user-images.githubusercontent.com/1055125/119263284-a9eae280-bb9b-11eb-815c-dadc1fdb67a4.png">

@gir-bot remove S: triage

**Comment by RoyiAvital** [comment]
Hi,

This is my current `YAML`:

```
---
    # Meta Data
    Title: Wind Speed Estimation Algorithm - Prototype - Report
    Summary: Report about Fixel's ML Algorithm for Wind Speed Estimation
    Author:
        - Royi Avital (RoyiAvital@fixelalgorithms.com)
        - Or Yair (OrYair@fixelalgorithms.com)

    # Settings
    settings:
        enable_uml: true
        markdown_extensions:
          - markdown.extensions.footnotes
          - markdown.extensions.fenced_code
          - markdown.extensions.tables
          - markdown.extensions.admonition
          - markdown.extensions.toc:
                title: Table of Contents
                toc_depth: 2-3
          - pymdownx.b64
          - pymdownx.arithmatex:
                generic: true
                smart_dollar: false
        allow_css_overrides: true
---
```

Everything else works but `b64`.
I think it is better to make things coherent, or everything should not work or `b64` should also work.

By the way, I copied the `YAML` and indention from [your documentation](https://facelessuser.github.io/MarkdownPreview/usage/#special-yaml-key-names):

![image](https://user-images.githubusercontent.com/7347975/119269550-f0265d00-bc00-11eb-96dc-d2909f45277c.png)

By the way, what's the difference between using `b64` and `"image_path_conversion": "base64",`?
It seems they can do the same (At first thought `b64` supports non local files [URL] but documentation requires local files).

Thank you for assisting me with this.
This is truly a great package (I'd be happy if you had a PayPal Me link for support).
