### ISSUE TITLE
The `attr_list` Is Not Applied

### ISSUE THREAD

**Issue by RoyiAvital** [facelessuser/MarkdownPreview#171]
I have a MarkDown document configured as:

```
---
# Meta Data
title: My Title
summary: Some summary.
description: Some description.

# Settings
settings:
    allow_css_overrides: true
    image_path_conversion: base64
    strip_yaml_front_matter: true

    js:
        - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js
        - res://MarkdownPreview/js/math_config.js
        - https://unpkg.com/mermaid@10.3.0/dist/mermaid.min.js
        # - res://MarkdownPreview/js/mermaid_config.js
        # - res://MarkdownPreview/js/mermaid.js

    markdown_extensions:
        - markdown.extensions.abbr
        - markdown.extensions.admonition
        - markdown.extensions.attr_list
        - markdown.extensions.def_list
        - markdown.extensions.footnotes
        - markdown.extensions.md_in_html
        - markdown.extensions.meta
        - markdown.extensions.sane_lists
        - markdown.extensions.smarty
        - markdown.extensions.tables
        - markdown.extensions.toc:
            title: Table of Contents
            toc_depth: 2-3
        - markdown.extensions.wikilinks
        - markdown_captions.markdown_captions
        - pymdownx.arithmatex:
            generic: true
            smart_dollar: false
        - pymdownx.betterem
        - pymdownx.emoji:
            options:
                attributes:
                    align: absmiddle
                    height: 20px
                    width: 20px
        - pymdownx.magiclink:
            repo_url_shortener: true
            repo_url_shorthand: true
        - pymdownx.mark
        - pymdownx.superfences:
            custom_fences:
                - name: mermaid
                  class: mermaid
                  # format: !!python/name:pymdownx.superfences.fence_code_format
                  format: !!python/name:pymdownx.superfences.fence_div_format
        - pymdownx.tasklist
        - pymdownx.tilde:
            subscript: false
---

my text {: class="foo bar"}.
```

The output doesn't apply the class to the text.
More than, that, is just appears as `my text {: class="foo bar"}.`.

I am following the documentation in https://python-markdown.github.io/extensions/attr_list/.
