### ISSUE TITLE
Possible to change the width of output page?

### ISSUE THREAD

**Issue by kurtontheway** [facelessuser/MarkdownPreview#49]
Great Package! but how can I change the width of rendered page? or make the page width adaptive to web browser?

**Comment by hadisfr** [comment]
You can use custom css to change width of the rendered page, e.g.:
```css
body {
    width: 980px;
}
```
or
```css
body {
    width: initial;
    padding: 16px 26px;
}
```
Take a look at [including-css at docs](https://facelessuser.github.io/MarkdownPreview/usage/#including-css) for adding custom css files to output.

You can use more complicated css rules with `@media` queries or etc, of course.
